### ISSUE TITLE
블로그 웹으로 접근 시 링크가 없다고 떠요

### ISSUE THREAD

**Issue by HongSJae** [rlaisqls/blog#9]
![image](https://github.com/user-attachments/assets/c33c226c-2a4b-449a-9a19-8bf873491dc3)

**Comment by rlaisqls** [comment]
도메인이 만료됐는데 갱신 비용이 비싸서 고민 중입니다ㅠ;

**Comment by rlaisqls** [comment]
고민 끝나서 재배포 했습니다 
https://blog.rlaisqls.com
